version: '3.8'
services:
  backend:
    container_name: 'ppbackend'
    build:
      context: ./server
      dockerfile: ../server-dockerfile
    env_file:
      - ./server/.env
    command: npm start
    ports:
      - '3333:3333'
    # expose:
    #   - '3333'
    volumes:
      - .:/src
      - /app/node_modules
    restart: always
    tty: true # allows color console output
    depends_on:
      - postgres
    networks:
      - ppnet
  frontend:
    container_name: 'ppfrontend'
    build:
      context: ./client
      dockerfile: ../client-dockerfile
    command: npm start
    ports:
      - '3000:3000'
    # expose:
    #   - '3333'
    volumes:
      - .:/src
      - /app/node_modules
    restart: always
    tty: true # allows color console output
    depends_on:
      - postgres
      - backend
    networks:
      - ppnet
  postgres:
    container_name: 'postgresdb'
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: 'ppdb'
      POSTGRES_USER: 'ppuser'
      POSTGRES_PASSWORD: 'VerySecurePassword'
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    networks:
      - ppnet
    # expose:
    #   - '5455'
    ports:
      - '5455:5432'
    volumes:
      - postgresdb:/postgresql/data
volumes:
  postgresdb:
networks:
  ppnet:
    name: ppnet
